// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-B3iYsCU-KXksZO9U8N3AtnEveHrCalo',
    appId: '1:838527465535:web:6fb443ca5b84dacb06e08a',
    messagingSenderId: '838527465535',
    projectId: 'doc-trial-2f6e0',
    authDomain: 'doc-trial-2f6e0.firebaseapp.com',
    storageBucket: 'doc-trial-2f6e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIxLhfoDnNxsMovyvVPWOhjYwQdrdypC4',
    appId: '1:838527465535:android:2b9c05151530d39106e08a',
    messagingSenderId: '838527465535',
    projectId: 'doc-trial-2f6e0',
    storageBucket: 'doc-trial-2f6e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6gYokBCvndLKl--mAYn0gb3uMqMcqFcA',
    appId: '1:838527465535:ios:82920dece07fad7206e08a',
    messagingSenderId: '838527465535',
    projectId: 'doc-trial-2f6e0',
    storageBucket: 'doc-trial-2f6e0.appspot.com',
    iosClientId: '838527465535-u3d4tmejj363v3qll8k1pscovnr1oaqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.docTrial',
  );
}
